auto: true
# gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"    
    
markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github_liuyingjun
url: http://lol666666.github.io
feed: /atom.xml
author_info: <a href="http://lol666666.github.io/">yingjunli</a>

myblog:
  gavatar: images/22.jpg
  gpname: liuyingjun
  linkedin: http://www.linkedin.com/in/liuyingjun
  github: https://github.com/lol666666
  email: mailto:liuyingjun.engineer@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books,java,android,iOS,php,jvm,js]
